INSERT INTO users (username, teammate) VALUES ('Bob Smith', 'Sarah Baker');
INSERT INTO languages (username, JAVA, CPP, SQL, HTML, PHP, Javascript, Bash,                              Git, Mongo, WSS, GIS, Python, PMO) VALUES ('Bob Smith', 'JAVA', 'CPP','','',                              '','','','','','','','Python','' );
INSERT INTO times (username, mon8to10, mon10to12, mon12to2, mon2to4,mon4to6,tue8to10,                              tue10to12,tue12to2,tue2to4,tue4to6) VALUES                              ('Bob Smith','Monday 8 AM to 10 AM', 'Monday 10 AM to 12 PM', 'Monday 12PM to 2 PM','Monday 2 PM to 4 PM','Monday 4 PM to 6 PM','','','','',''                              );
INSERT INTO users (username, teammate) VALUES ('Sam Smith', 'Mary Sue');
INSERT INTO languages (username, JAVA, CPP, SQL, HTML, PHP, Javascript, Bash,                              Git, Mongo, WSS, GIS, Python, PMO) VALUES ('Sam Smith', 'JAVA', '','SQL','HTML',                              'PHP','Javascript','Bash','Git','','','','Python','' );
INSERT INTO times (username, mon8to10, mon10to12, mon12to2, mon2to4,mon4to6,tue8to10,                              tue10to12,tue12to2,tue2to4,tue4to6) VALUES                              ('Sam Smith','Monday 8 AM to 10 AM', 'Monday 10 AM to 12 PM', 'Monday 12PM to 2 PM','','','Tuesday 8 AM to 10 AM','Tuesday 10 AM to 12 PM','Tuesday 12 PM to 2 PM','',''                              );
INSERT INTO users (username, teammate) VALUES ('Jiahan Noel', 'Billy Smith');
INSERT INTO languages (username, JAVA, CPP, SQL, HTML, PHP, Javascript, Bash,                              Git, Mongo, WSS, GIS, Python, PMO) VALUES ('Jiahan Noel', '', 'CPP','SQL','HTML',                              '','','Bash','','Mongo','WSS','','Python','' );
INSERT INTO times (username, mon8to10, mon10to12, mon12to2, mon2to4,mon4to6,tue8to10,                              tue10to12,tue12to2,tue2to4,tue4to6) VALUES                              ('Jiahan Noel','Monday 8 AM to 10 AM', 'Monday 10 AM to 12 PM', 'Monday 12PM to 2 PM','','','','Tuesday 10 AM to 12 PM','Tuesday 12 PM to 2 PM','','Tuesday 4 PM to 6 PM'                              );
